apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: SkyWatch
  annotations:
    github.com/project-slug: MohammedKaleemullah/SkyWatch
spec:
  type: other
  lifecycle: unknown
  owner: MohammedKaleemullah
